config/routes.rb
Rails.application.routes.draw do
  resources :medical_records
  resources :appointments
  resources :departments
  resources :doctors
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :patient
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_medical_record, only: %i[ show edit update destroy ]

  # GET /medical_records or /medical_records.json
  def index
    @medical_records = MedicalRecord.all
  end

  # GET /medical_records/1 or /medical_records/1.json
  def show
  end

  # GET /medical_records/new
  def new
    @medical_record = MedicalRecord.new
  end

  # GET /medical_records/1/edit
  def edit
  end

  # POST /medical_records or /medical_records.json
  def create
    @medical_record = MedicalRecord.new(medical_record_params)

    respond_to do |format|
      if @medical_record.save
        format.html { redirect_to medical_record_url(@medical_record), notice: "Medical record was successfully created." }
        format.json { render :show, status: :created, location: @medical_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_records/1 or /medical_records/1.json
  def update
    respond_to do |format|
      if @medical_record.update(medical_record_params)
        format.html { redirect_to medical_record_url(@medical_record), notice: "Medical record was successfully updated." }
        format.json { render :show, status: :ok, location: @medical_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1 or /medical_records/1.json
  def destroy
    @medical_record.destroy

    respond_to do |format|
      format.html { redirect_to medical_records_url, notice: "Medical record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_record
      @medical_record = MedicalRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_record_params
      params.require(:medical_record).permit(:patient_id, :diagnosis, :treatment_details)
    end
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/views/medical_records/_form.html.erb
<%= form_with(model: medical_record) do |form| %>
  <% if medical_record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
        <% medical_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.text_field :patient_id %>
  </div>

  <div>
    <%= form.label :diagnosis, style: "display: block" %>
    <%= form.text_area :diagnosis %>
  </div>

  <div>
    <%= form.label :treatment_details, style: "display: block" %>
    <%= form.text_area :treatment_details %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_records/_medical_record.html.erb
<div id="<%= dom_id medical_record %>">
  <p>
    <strong>Patient:</strong>
    <%= medical_record.patient_id %>
  </p>

  <p>
    <strong>Diagnosis:</strong>
    <%= medical_record.diagnosis %>
  </p>

  <p>
    <strong>Treatment details:</strong>
    <%= medical_record.treatment_details %>
  </p>

</div>

app/views/medical_records/edit.html.erb
<h1>Editing medical record</h1>

<%= render "form", medical_record: @medical_record %>

<br>

<div>
  <%= link_to "Show this medical record", @medical_record %> |
  <%= link_to "Back to medical records", medical_records_path %>
</div>

app/views/medical_records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Medical records</h1>

<div id="medical_records">
  <% @medical_records.each do |medical_record| %>
    <%= render medical_record %>
    <p>
      <%= link_to "Show this medical record", medical_record %>
    </p>
  <% end %>
</div>

<%= link_to "New medical record", new_medical_record_path %>

app/views/medical_records/new.html.erb
<h1>New medical record</h1>

<%= render "form", medical_record: @medical_record %>

<br>

<div>
  <%= link_to "Back to medical records", medical_records_path %>
</div>

app/views/medical_records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medical_record %>

<div>
  <%= link_to "Edit this medical record", edit_medical_record_path(@medical_record) %> |
  <%= link_to "Back to medical records", medical_records_path %>

  <%= button_to "Destroy this medical record", @medical_record, method: :delete %>
</div>