config/routes.rb
Rails.application.routes.draw do
  resources :medical_records
  resources :appointments
  resources :departments
  resources :doctors
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    doctors = Doctor.all
    render json: doctors
  end

  # GET /doctors/1 or /doctors/1.json
  def show
    doctor = Doctor.find_by(id: params[:id])
     if doctor
      render json: doctor
     else
      render json: {"error": "User not found"}
     end
  end

 

  # POST /doctors or /doctors.json
  def create
    doctor = Doctor.create(doctor_params)

    if doctor
      render json: doctor
    else
      render json: {"error": "cannot be created" }, status: :not_acceptable
    end

    
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    doctor = Doctor.find_by(id: params[:id])

    doctor.update(doctor_params)

    if doctor
      render json: doctor
    else
      render json: {"error": "cannot be updated" }
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    doctor = Doctor.find_by(id: params[:id])
    doctor.destroy

    head :no_content
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.permit(:name, :age, :gender, :phone_number, :email, :specialization, :available, :is_active, :password_digest, :role)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <p>
    <strong>Name:</strong>
    <%= doctor.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= doctor.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= doctor.gender %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= doctor.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= doctor.email %>
  </p>

  <p>
    <strong>Specialization:</strong>
    <%= doctor.specialization %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= doctor.available %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= doctor.is_active %>
  </p>

</div>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :specialization, style: "display: block" %>
    <%= form.text_field :specialization %>
  </div>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Show this doctor", @doctor %> |
  <%= link_to "Back to doctors", doctors_path %>
</div>

app/views/doctors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Doctors</h1>

<div id="doctors">
  <% @doctors.each do |doctor| %>
    <%= render doctor %>
    <p>
      <%= link_to "Show this doctor", doctor %>
    </p>
  <% end %>
</div>

<%= link_to "New doctor", new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Back to doctors", doctors_path %>
</div>

app/views/doctors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @doctor %>

<div>
  <%= link_to "Edit this doctor", edit_doctor_path(@doctor) %> |
  <%= link_to "Back to doctors", doctors_path %>

  <%= button_to "Destroy this doctor", @doctor, method: :delete %>
</div>